\set ON_ERROR_STOP on

/*
RoadVision v1.2.1 — kayıpsız tespit türü normalizasyonu
PostgreSQL 17, DB schema_info sürümü: 3

Amaç:
  - 4 aktif model ve 20 bilinen tespit türünü referans kataloğuna almak.
  - Model/sınıf metnini type_id ile sorgulanabilir bir çalışma zamanı
    sözlüğüne bağlamak.
  - confidence, bbox ve area_ratio değerlerini hiç dönüştürmeden korumak.
  - Katalog dışı model/sınıfları kaybetmeden is_catalogued=FALSE olarak
    sözlüğe eklemek.
  - V1.2 INSERT ve raporları için model_id/class_name kolonlarını v3 boyunca
    korumak; birleşik FK ile bu alanların type_id ile çelişmesini engellemek.

Bu dosya DB şema 2 veya daha önce uygulanmış DB şema 3 veritabanında güvenle tekrar
çalıştırılabilir. Uygulamadan önce eski RoadVision süreçlerini kapatın ve
pg_dump yedeği alın.
*/

BEGIN;

SELECT pg_advisory_xact_lock(1385428466);

DO $$
DECLARE
    v_version INTEGER;
BEGIN
    IF to_regclass('schema_info') IS NULL
       OR to_regclass('detection_events') IS NULL
       OR to_regclass('detected_objects') IS NULL THEN
        RAISE EXCEPTION
            'RoadVision v2 çekirdek tabloları bulunamadı; önce db/schema.sql uygulayın';
    END IF;

    SELECT COALESCE(MAX(version), 0)
    INTO v_version
    FROM schema_info;

    IF v_version NOT IN (2, 3) THEN
        RAISE EXCEPTION
            'v1.2.1 migration yalnız DB şema 2 veya 3 üzerinde çalışır; bulunan sürüm: %',
            v_version;
    END IF;
END $$;

CREATE TABLE IF NOT EXISTS roadvision_model_catalog (
    model_id TEXT PRIMARY KEY,
    display_name TEXT NOT NULL,
    task TEXT NOT NULL CHECK (task IN ('semantic', 'detect')),
    class_count INTEGER NOT NULL CHECK (class_count > 0),
    input_size INTEGER NOT NULL CHECK (input_size > 0),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS roadvision_detection_type_catalog (
    model_id TEXT NOT NULL
        REFERENCES roadvision_model_catalog(model_id) ON DELETE CASCADE,
    class_index INTEGER NOT NULL CHECK (class_index >= 0),
    class_name TEXT NOT NULL,
    display_name TEXT NOT NULL,
    PRIMARY KEY (model_id, class_index),
    UNIQUE (model_id, class_name)
);

INSERT INTO roadvision_model_catalog
    (model_id, display_name, task, class_count, input_size, active)
VALUES
    ('roadline',       'Yol Çizgisi Segmentasyonu',    'semantic',  1, 1024, TRUE),
    ('traffic_sign',   'Tabela ve Trafik Işığı',       'detect',   16,  640, TRUE),
    ('pothole',        'Çukur ve Rögar Kapağı Tespiti', 'detect',    2,  768, TRUE),
    ('marking_damage', 'Yol İşareti Hasarı',           'detect',    1,  640, TRUE)
ON CONFLICT (model_id) DO UPDATE SET
    display_name = EXCLUDED.display_name,
    task = EXCLUDED.task,
    class_count = EXCLUDED.class_count,
    input_size = EXCLUDED.input_size,
    active = EXCLUDED.active,
    updated_at = now();

INSERT INTO roadvision_detection_type_catalog
    (model_id, class_index, class_name, display_name)
VALUES
    ('roadline',        0, 'roadline',            'Yol çizgisi'),
    ('traffic_sign',    0, '20',                  'Hız sınırı 20'),
    ('traffic_sign',    1, '30',                  'Hız sınırı 30'),
    ('traffic_sign',    2, 'dur',                 'Dur'),
    ('traffic_sign',    3, 'durak',               'Durak'),
    ('traffic_sign',    4, 'girisyok',            'Giriş yok'),
    ('traffic_sign',    5, 'ilerisag',            'İleri veya sağ'),
    ('traffic_sign',    6, 'ilerisol',            'İleri veya sol'),
    ('traffic_sign',    7, 'kirmizi',             'Kırmızı ışık'),
    ('traffic_sign',    8, 'park',                'Park'),
    ('traffic_sign',    9, 'parkyasak',           'Park yasak'),
    ('traffic_sign',   10, 'sag',                 'Sağ yön'),
    ('traffic_sign',   11, 'sagadonulmez',        'Sağa dönülmez'),
    ('traffic_sign',   12, 'sari',                'Sarı ışık'),
    ('traffic_sign',   13, 'sol',                 'Sol yön'),
    ('traffic_sign',   14, 'soladonulmez',        'Sola dönülmez'),
    ('traffic_sign',   15, 'yesil',               'Yeşil ışık'),
    ('pothole',         0, 'pothole',             'Çukur'),
    ('pothole',         1, 'manhole_cover',       'Rögar kapağı'),
    ('marking_damage',  0, 'road_marking_damage', 'Yol işareti hasarı')
ON CONFLICT (model_id, class_index) DO UPDATE SET
    class_name = EXCLUDED.class_name,
    display_name = EXCLUDED.display_name;

CREATE TABLE IF NOT EXISTS detection_types (
    type_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    model_id TEXT NOT NULL,
    class_index INTEGER CHECK (class_index >= 0),
    class_name TEXT NOT NULL,
    display_name TEXT NOT NULL,
    is_catalogued BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (model_id, class_name),
    UNIQUE (model_id, class_index),
    UNIQUE (type_id, model_id, class_name)
);

INSERT INTO detection_types
    (model_id, class_index, class_name, display_name, is_catalogued)
SELECT model_id, class_index, class_name, display_name, TRUE
FROM roadvision_detection_type_catalog
ON CONFLICT (model_id, class_name) DO UPDATE SET
    class_index = EXCLUDED.class_index,
    display_name = EXCLUDED.display_name,
    is_catalogued = TRUE;

-- V2 verisindeki katalog dışı türler de ayrı kimlikleriyle korunur.
INSERT INTO detection_types
    (model_id, class_index, class_name, display_name, is_catalogued)
SELECT DISTINCT model_id, NULL::INTEGER, class_name, class_name, FALSE
FROM detected_objects
ON CONFLICT (model_id, class_name) DO NOTHING;

CREATE OR REPLACE FUNCTION fn_get_or_create_detection_type(
    p_model_id TEXT,
    p_class_name TEXT
) RETURNS INTEGER
LANGUAGE plpgsql AS $$
DECLARE
    v_type_id INTEGER;
BEGIN
    SELECT type_id
    INTO v_type_id
    FROM detection_types
    WHERE model_id = p_model_id
      AND class_name = p_class_name;

    IF v_type_id IS NOT NULL THEN
        RETURN v_type_id;
    END IF;

    INSERT INTO detection_types
        (model_id, class_index, class_name, display_name, is_catalogued)
    VALUES
        (p_model_id, NULL, p_class_name, p_class_name, FALSE)
    ON CONFLICT (model_id, class_name) DO NOTHING
    RETURNING type_id INTO v_type_id;

    IF v_type_id IS NULL THEN
        SELECT type_id
        INTO v_type_id
        FROM detection_types
        WHERE model_id = p_model_id
          AND class_name = p_class_name;
    END IF;

    RETURN v_type_id;
END $$;

ALTER TABLE detected_objects
    ADD COLUMN IF NOT EXISTS type_id INTEGER;

UPDATE detected_objects AS o
SET type_id = t.type_id
FROM detection_types AS t
WHERE o.type_id IS NULL
  AND t.model_id = o.model_id
  AND t.class_name = o.class_name;

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM detected_objects WHERE type_id IS NULL) THEN
        RAISE EXCEPTION
            'detected_objects type_id backfill eksik; migration geri alındı';
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conrelid = 'detected_objects'::regclass
          AND conname = 'detected_objects_type_id_fkey'
    ) THEN
        ALTER TABLE detected_objects
            ADD CONSTRAINT detected_objects_type_id_fkey
            FOREIGN KEY (type_id, model_id, class_name)
            REFERENCES detection_types(type_id, model_id, class_name)
            ON UPDATE RESTRICT
            ON DELETE RESTRICT
            NOT VALID;
    END IF;
END $$;

ALTER TABLE detected_objects
    VALIDATE CONSTRAINT detected_objects_type_id_fkey;

ALTER TABLE detected_objects
    ALTER COLUMN type_id SET NOT NULL;

CREATE OR REPLACE FUNCTION fn_fill_detected_object_type_id()
RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    IF NEW.type_id IS NULL THEN
        NEW.type_id := fn_get_or_create_detection_type(
            NEW.model_id,
            NEW.class_name
        );
    END IF;
    RETURN NEW;
END $$;

DROP TRIGGER IF EXISTS trg_fill_detected_object_type_id
    ON detected_objects;
CREATE TRIGGER trg_fill_detected_object_type_id
    BEFORE INSERT OR UPDATE OF type_id, model_id, class_name
    ON detected_objects
    FOR EACH ROW
    EXECUTE FUNCTION fn_fill_detected_object_type_id();

DROP VIEW IF EXISTS vw_roadvision_daily_detection_counts;
DROP VIEW IF EXISTS vw_roadvision_detection_type_counts;
DROP VIEW IF EXISTS vw_detected_objects_flat;

CREATE INDEX IF NOT EXISTS idx_detection_events_ts
    ON detection_events (ts);
CREATE INDEX IF NOT EXISTS idx_detected_objects_ts
    ON detected_objects (ts);
CREATE INDEX IF NOT EXISTS idx_detected_objects_type_ts
    ON detected_objects (type_id, ts);

CREATE OR REPLACE VIEW vw_detected_objects_flat AS
SELECT
    o.id,
    o.event_id,
    o.ts,
    o.run_id,
    t.model_id,
    t.class_name,
    o.confidence,
    o.bbox,
    o.area_ratio
FROM detected_objects AS o
JOIN detection_types AS t
    ON t.type_id = o.type_id
   AND t.model_id = o.model_id
   AND t.class_name = o.class_name;

CREATE OR REPLACE VIEW vw_roadvision_model_inventory AS
SELECT
    m.model_id,
    m.display_name,
    m.task,
    m.input_size,
    m.class_count AS declared_type_count,
    count(t.class_index)::INTEGER AS catalog_type_count,
    (m.class_count = count(t.class_index)) AS catalog_is_complete,
    m.active
FROM roadvision_model_catalog AS m
LEFT JOIN roadvision_detection_type_catalog AS t
    ON t.model_id = m.model_id
GROUP BY
    m.model_id,
    m.display_name,
    m.task,
    m.input_size,
    m.class_count,
    m.active;

CREATE OR REPLACE VIEW vw_roadvision_detection_type_counts AS
SELECT
    t.model_id,
    c.class_index,
    t.class_name,
    t.display_name,
    t.is_catalogued,
    count(o.id)::BIGINT AS total_count,
    count(o.id) FILTER (
        WHERE o.ts >= now() - interval '24 hours'
    )::BIGINT AS last_24h_count,
    count(o.id) FILTER (
        WHERE o.ts >= now() - interval '7 days'
    )::BIGINT AS last_7d_count,
    round(avg(o.confidence)::NUMERIC, 4) AS avg_confidence,
    min(o.ts) AS first_seen_at,
    max(o.ts) AS last_seen_at
FROM detection_types AS t
LEFT JOIN roadvision_detection_type_catalog AS c
    ON c.model_id = t.model_id
   AND c.class_name = t.class_name
LEFT JOIN detected_objects AS o
    ON o.type_id = t.type_id
GROUP BY
    t.model_id,
    c.class_index,
    t.class_name,
    t.display_name,
    t.is_catalogued;

CREATE OR REPLACE VIEW vw_roadvision_daily_detection_counts AS
SELECT
    date_trunc('day', o.ts) AS day,
    t.model_id,
    t.class_name,
    count(*)::BIGINT AS detection_count,
    round(avg(o.confidence)::NUMERIC, 4) AS avg_confidence
FROM detected_objects AS o
JOIN detection_types AS t
    ON t.type_id = o.type_id
GROUP BY
    date_trunc('day', o.ts),
    t.model_id,
    t.class_name;

CREATE OR REPLACE VIEW vw_roadvision_unknown_detection_types AS
SELECT
    t.type_id,
    t.model_id,
    t.class_name,
    count(o.id)::BIGINT AS detection_count,
    min(o.ts) AS first_seen_at,
    max(o.ts) AS last_seen_at
FROM detection_types AS t
LEFT JOIN detected_objects AS o
    ON o.type_id = t.type_id
WHERE NOT t.is_catalogued
GROUP BY
    t.type_id,
    t.model_id,
    t.class_name;

CREATE OR REPLACE VIEW vw_roadvision_capture_summary AS
SELECT
    c.capture_id,
    c.ts,
    c.run_id,
    c.source_name,
    c.source_kind,
    c.frame_sequence,
    c.is_reprocess,
    string_agg(
        m.model_id || ' (' || m.object_count::TEXT || ')',
        ', ' ORDER BY m.model_id
    ) AS models,
    o.byte_size AS original_bytes,
    a.byte_size AS annotated_bytes,
    (o.byte_size + a.byte_size)::BIGINT AS referenced_bytes
FROM media_captures AS c
JOIN media_capture_models AS m
    ON m.capture_id = c.capture_id
JOIN media_blobs AS o
    ON o.id = c.original_media_id
JOIN media_blobs AS a
    ON a.id = c.annotated_media_id
GROUP BY
    c.capture_id,
    c.ts,
    c.run_id,
    c.source_name,
    c.source_kind,
    c.frame_sequence,
    c.is_reprocess,
    o.byte_size,
    a.byte_size;

COMMENT ON TABLE roadvision_model_catalog IS
    'RoadVision tarafından tanımlanmış aktif model envanteri.';
COMMENT ON TABLE roadvision_detection_type_catalog IS
    'Dört aktif modelde beklenen 20 tespit türünün referans kataloğu.';
COMMENT ON TABLE detection_types IS
    'Bilinen ve çalışma zamanında gözlenen tüm model/sınıf çiftlerinin sözlüğü.';
COMMENT ON COLUMN detected_objects.type_id IS
    'model_id/class_name çiftiyle birleşik FK üzerinden doğrulanan tür kimliği.';
COMMENT ON VIEW vw_detected_objects_flat IS
    'V2 detected_objects kolon sözleşmesini aynı sıra ve tiplerle sunar.';
COMMENT ON VIEW vw_roadvision_detection_type_counts IS
    'Bilinen ve bilinmeyen türler için toplam, 24 saat ve 7 gün sayımları.';
COMMENT ON VIEW vw_roadvision_unknown_detection_types IS
    'Katalogda bulunmayan fakat veride gözlenen türlerin bakım kuyruğu.';

INSERT INTO schema_info (version)
VALUES (3)
ON CONFLICT (version) DO NOTHING;

DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM detected_objects AS o
        LEFT JOIN detection_types AS t
            ON t.type_id = o.type_id
           AND t.model_id = o.model_id
           AND t.class_name = o.class_name
        WHERE t.type_id IS NULL
    ) THEN
        RAISE EXCEPTION
            'type_id/model_id/class_name doğrulaması başarısız; migration geri alındı';
    END IF;

    IF (
        SELECT count(*)
        FROM roadvision_detection_type_catalog
    ) <> 20 THEN
        RAISE EXCEPTION
            'Referans katalog 20 tür içermiyor; migration geri alındı';
    END IF;

    IF EXISTS (
        SELECT 1
        FROM vw_roadvision_model_inventory
        WHERE NOT catalog_is_complete
    ) THEN
        RAISE EXCEPTION
            'Model kataloğu eksik; migration geri alındı';
    END IF;
END $$;

COMMIT;

ANALYZE roadvision_model_catalog;
ANALYZE roadvision_detection_type_catalog;
ANALYZE detection_types;
ANALYZE detected_objects;

-- ============================================================================
-- HAZIR KONTROL VE RAPOR SORGULARI
-- ============================================================================

-- Q1: Aktif model ve tanımlı tespit türü sayısı (beklenen: 4 / 20).
SELECT
    (SELECT count(*) FROM roadvision_model_catalog WHERE active)
        AS active_model_count,
    (SELECT count(*) FROM detection_types WHERE is_catalogued)
        AS catalogued_detection_type_count;

-- Q2: Model başına katalog bütünlüğü.
SELECT *
FROM vw_roadvision_model_inventory
ORDER BY model_id;

-- Q3: Son 24 saatte tespit türü sayıları ve ortalama güven.
SELECT
    model_id,
    class_name,
    display_name,
    last_24h_count,
    avg_confidence
FROM vw_roadvision_detection_type_counts
WHERE last_24h_count > 0
ORDER BY last_24h_count DESC, model_id, class_name;

-- Q4: Belirli türün saatlik dağılımı.
SELECT
    date_trunc('hour', o.ts) AS hour,
    count(*) AS detection_count,
    round(avg(o.confidence)::NUMERIC, 4) AS avg_confidence
FROM detected_objects AS o
JOIN detection_types AS t
    ON t.type_id = o.type_id
WHERE t.model_id = 'pothole'
  AND t.class_name = 'pothole'
  AND o.ts >= now() - interval '24 hours'
GROUP BY date_trunc('hour', o.ts)
ORDER BY hour;

-- Q5: Günlük model/tür sayımları.
SELECT *
FROM vw_roadvision_daily_detection_counts
WHERE day >= date_trunc('day', now()) - interval '30 days'
ORDER BY day DESC, model_id, class_name;

-- Q6: Henüz kataloglanmamış türler.
SELECT *
FROM vw_roadvision_unknown_detection_types
ORDER BY last_seen_at DESC NULLS LAST, model_id, class_name;

-- Q7: Olay ve tekil nesne sayıları.
SELECT
    e.model_id,
    count(DISTINCT e.id) AS event_count,
    count(o.id) AS detected_object_count,
    round(avg(e.elapsed_ms)::NUMERIC, 2) AS avg_elapsed_ms
FROM detection_events AS e
LEFT JOIN detected_objects AS o
    ON o.event_id = e.id
WHERE e.ts >= now() - interval '24 hours'
GROUP BY e.model_id
ORDER BY detected_object_count DESC;

-- Q8: Son 50 tespit nesnesi.
SELECT
    o.id,
    o.ts,
    o.run_id,
    t.model_id,
    t.class_name,
    o.confidence,
    o.bbox,
    o.area_ratio
FROM detected_objects AS o
JOIN detection_types AS t
    ON t.type_id = o.type_id
ORDER BY o.ts DESC, o.id DESC
LIMIT 50;

-- Q9: Eski metin kolonları ile type_id arasında tutarsızlık olmamalı.
SELECT o.id, o.type_id, o.model_id, o.class_name
FROM detected_objects AS o
LEFT JOIN detection_types AS t
    ON t.type_id = o.type_id
   AND t.model_id = o.model_id
   AND t.class_name = o.class_name
WHERE t.type_id IS NULL;

-- Q10: Şema sürümleri.
SELECT version, applied_at
FROM schema_info
ORDER BY version;
